- name: Add node to karmada/k3s
  block:
    - name: Verify node info is present before adding
      assert:
        that: inventory_hostname in chutes_nodes
        fail_msg: Node information for {{ inventory_hostname }} is not present. Run the 'get-node-info' tag to resolve if this node still exists in microk8s, otherwise add manually.
        success_msg: Found information for {{ inventory_hostname }}
 
    - name: Run add node command remotely
      ansible.builtin.command: >
        chutes-miner add-node --name {{ inventory_name }}  --hotkey {{ remote_hotkey_path }}
        --validator 5Dt7HZ7Zpw4DppPxFM7Ke3Cm7sDAWhsZXmM5ZAmE7dSVJbcQ
        --hourly-cost {{ chutes_nodes[inventory_name]['hourly_cost'] }}
        --gpu-short-ref {{ chutes_nodes[inventory_name]['gpu_type'] }}
      register: remote_add_output
      failed_when: remote_add_output.rc != 0
      changed_when: false
      when: not run_cli_locally | default(true)

    - name: Run add node command locally
      ansible.builtin.command: >
        chutes-miner add-node --name {{ inventory_name }}  --hotkey {{ hotkey_path }}
        --miner-api http://{{ ansible_host }}:{{ miner_api_port | default(32000) }}
        --validator 5Dt7HZ7Zpw4DppPxFM7Ke3Cm7sDAWhsZXmM5ZAmE7dSVJbcQ
        --hourly-cost {{ chutes_nodes[inventory_name]['hourly_cost'] }}
        --gpu-short-ref {{ chutes_nodes[inventory_name]['gpu_type'] }}
      register: local_add_output
      failed_when: local_add_output.rc != 0
      become: false
      changed_when: false
      delegate_to: localhost
      when: run_cli_locally | default(false)

    - name: Set add variable
      ansible.builtin.set_fact:
        add_output: "{{ remote_add_output | default(local_add_output) }}"

    - name: Verify node added
      assert:
        that: add_output.rc == 0
        fail_msg: "Failed to add node {{ inventory_hostname }}"
        success_msg: "Successfully added {{ inventory_hostname }}"

