{{- $redisSecret := lookup "v1" "Secret" .Release.Namespace "redis-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.password.passwordKey }}: {{ if $redisSecret }}{{ index $redisSecret.data .Values.redis.password.passwordKey }}{{ else }}{{ default (randAlphaNum 32) .Values.redis.password.value | b64enc }}{{ end }}
---
{{- $postgresSecret := lookup "v1" "Secret" .Release.Namespace "postgres-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.postgres.database.passwordKey }}: {{ if $postgresSecret }}{{ index $postgresSecret.data .Values.postgres.database.passwordKey }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}