---
# Servers should be restarted sequientally to avoid etcd learner issues
# Agents have no such limitation

- name: Upgrade K3s Servers
  hosts: control
  become: true
  serial: 1
  roles:
    - role: k3s_upgrade

- name: Upgrade K3s Agents
  hosts: workers
  become: true
  roles:
    - role: k3s_upgrade
