---
# inventory.yml
all:
  children:
    control:
      hosts:
        chutes-miner-cpu-0:
          ansible_host: 10.0.0.1
    workers:
      hosts:
        chutes-miner-gpu-0:
          ansible_host: 10.0.0.2
        chutes-miner-gpu-1:
          ansible_host: 10.0.0.3
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/your_key.pem
    ssh_keys:
      - "ssh-rsa AAAAB3N... user@domain.com"
    # The username you want to use to login to those machines (and your public key will be added to).
    user: billybob

    # Local kubectl setup
    setup_local_kubeconfig: false
    controller_kubeconfig: ~/.kube/chutes.config
    controller_kubectl_staging_dir: "{{ '~/.kube' | expanduser }}/chutes-staging" # noqa var-naming[no-role-prefix]